### ISSUE TITLE
support setting icons for shortcuts

### ISSUE THREAD

**Issue by newville** [martinohanlon/shortcut#19]
First, I have some partial, incomplete scripts for making shortcuts for apps,  but this project looks much better thought out and I would like to be able to use it.  

But, of course, I have a few feature requests that I would like to be able to do:
  a) specify an icon file to use.
  b) better support for non-terminal Apps for MacOS.
  c) create a folder on the desktop containing several related Apps.

I have sciprts that can do these things.  From a quick look at the code, a) and b) look possible to add, and C may not be hard.   Would you be interested in having these features added?

**Comment by martinohanlon** [comment]
Thanks a lot @newville . They look like great features. I'll target for inclusion in the next release. :)

**Comment by Hamberfim** [comment]
It would be nice if you could add a usage flag to delete a shortcut from the menu or desktop. 
Perhaps documented as below"

usage: shortcut [-h] [-d] [-m] [del -m] [del -d] {del - a] target

Auto shortcut creator

positional arguments:
target         The target executable to create Desktop and Menu shortcuts

optional arguments:
-h, --help     show this help message and exit
-d, --desktop  Only create a desktop shortcut
-m, --menu     Only create a menu shortcut
[del -m]    Delete only a created a menu shortcut
[del -d]     Delete only a created a desktop shortcut
[del -a]     Delete BOTH a created a desktop and menu shortcut
