### ISSUE TITLE
Conda and venv support

### ISSUE THREAD

**Issue by kiwi0fruit** [martinohanlon/shortcut#8]
It would be nice to:

* have working shortcuts to apps in conda environments and virtualenv environments. This needs implementing 'smart' shortcut shell scripts that activate environment before running the executable (and deactivate after).
* support conda post-link scripts ([like these](https://github.com/conda-forge/widgetsnbextension-feedstock/tree/master/recipe)). This needs adding all new features support to the shortcut CLI.

**Comment by kiwi0fruit** [comment]
@martinohanlon I guess API in https://github.com/martinohanlon/shortcut/pull/7 would be fixated only after implementing features in this issue.

**Comment by kiwi0fruit** [comment]
Bad news. From https://conda.io/docs/user-guide/tasks/build-packages/link-scripts.html

Post-link and pre-unlink scripts should:

* Be avoided whenever possible.
* Not touch anything other than the files being installed.
* Not write anything to stdout or stderr, unless an error occurs.
* Not depend on any installed or to be installed conda packages.
* Depend only on simple system tools such as rm, cp, mv and ln.

So using shortcut in conda is limited. And lots of new features added by me are useless... It might be that most of new features are redundant - it's better to install a packageX - then install packageX-shortcuts package.

**Comment by kiwi0fruit** [comment]
@martinohanlon See comment above. Summary: there are alike limitations in conda packages as in wheels. I don't know if the restrictions are obligatory but it may be.

So the additions that are mentioned to work in setup.py are wery niche. So it's better target running shortcut not during install but after installing. So no virtual and entry_point functions are needed.

**Comment by kiwi0fruit** [comment]
@martinohanlon I'm gonna create a dummy pandoctools-shortcuts module and test if running scripts in it's setup.py in scenarios like `pip install pandoctools pandoctools-shortcuts` work without virtual complexity management

**Comment by kiwi0fruit** [comment]
Or adding new entry_point executable like pandoctools-shortcuts is also OK. And then run it after installation... I guess that's all we can get from pip and conda. Sadly, but custom post-installation commands are the the best option when installing python modules...

**Comment by kiwi0fruit** [comment]
@martinohanlon Or adding new entry_point executable like pandoctools-shortcuts is also OK. And then run it after installation... I guess that's all we can get from pip and conda. Sadly, but custom post-installation commands are the the best option when installing python modules...

**Comment by martinohanlon** [comment]
Indeed, these are the conclusions I came to when first developing shortcut. 

I originally developed it to create shortcuts for a beginners IDE called Mu. My hope was to automate shortcut creation but the restrictions on running post-install scripts for wheels meant this wasnt to be, so I changed track and made it as simple as possible, e.g. if you want to install Mu and create a shortcut for it you would run:

```
pip install mu-editor
shortcut mu
```

**Comment by kiwi0fruit** [comment]
@martinohanlon This way we don't really need logging errors mode: only `--silent` (no errors no logging). maybe we need `--debug` to see all errors at once logged to stderr, but it's not really needed for debugging.

**Comment by kiwi0fruit** [comment]
@martinohanlon Nope. I don't wanna give up. I still think that extra pypi source (not wheel) package is more convenient than running extra command in terminal.

So I'm going to test `pip install mypkg mypkg-ready`

**Comment by kiwi0fruit** [comment]
@martinohanlon `pip install mypkg mypkg-ready` succesfully works even if `mypkg`wasn't installed and even if it's a wheel.

**Comment by kiwi0fruit** [comment]
@martinohanlon this can even be used in conda yaml environment specification. `env.yaml`:
```yaml
# run: conda env create --file env.yml
name: test-env
dependencies:
- python>=3.6
- pip
- mypkg
- pip:
  - mypkg-ready
```
